### PR TITLE
change: improve read me

### PR DESCRIPTION
**Pull request by stavares843**
Minor suggestion on README.md 🔨

### CODE REVIEW

**Review by kairadiagne — APPROVED** [review]
Thanks!

**Review by raphkoebraam — APPROVED** [review]
🚀

**Comment by wetransferplatform** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>

  View more details on <a href="https://app.bitrise.io/build/b1637042-57f1-42ed-b1f7-9461dbc2e043" target="_blank">Bitrise</a>
  </td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>MockerTests: Executed 25 tests (0 failed, 0 retried, 0 skipped) in 1.633 seconds</td>
    </tr>
  </tbody>
</table>

## Code Coverage Report
| Name | Coverage ||
| --- | --- | --- |
Mocker.framework | 87.93% | ✅

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/swift">Danger Swift</a> against 9de0393e10089435cc3ebb757d19c3c7968dc665
</p>

**Review by BasThomas — APPROVED** [review]
Awesome, thank you @stavares843!

**Comment by wetransferplatform** [comment]
Congratulations! :tada: This was released as part of [Release 2.7.0](https://github.com/WeTransfer/Mocker/releases/tag/2.7.0) :rocket:<p align="right"><i>Generated by <a href="https://github.com/WeTransfer/GitBuddy">GitBuddy</a></i></p>

**Comment by wetransferplatform** [comment]
Congratulations! :tada: This was released as part of [Release 3.0.0](https://github.com/WeTransfer/Mocker/releases/tag/3.0.0) :rocket:<p align="right"><i>Generated by <a href="https://github.com/WeTransfer/GitBuddy">GitBuddy</a></i></p>

**Pull request merged**
