### PR TITLE
Merge release 2.0.2 into master

### PR DESCRIPTION
**Pull request by ghost**
Containing all the changes for our [**2.0.2 Release**](https://github.com/WeTransfer/Mocker/releases/tag/2.0.2).

### CODE REVIEW

**Comment by ghost** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>

  View more details on <a href="https://app.bitrise.io/build/5c22d25795991ac9" target="_blank">Bitrise</a>
  </td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>Mocker: Executed 16 tests, with 0 failures (0 unexpected) in 1.766 (1.775) seconds</td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/swift">Danger Swift</a> against 37a90f73cf0cd9059d40ba0fb72891eb200ebc21
</p>

**Review by kairadiagne — APPROVED** [review]

**Comment by ghost** [comment]
Congratulations! :tada: This was released as part of [Release 2.1.0](https://github.com/WeTransfer/Mocker/releases/tag/2.1.0) :rocket:

**Comment by ghost** [comment]
Congratulations! :tada: This was released as part of [Release 2.1.0](https://github.com/WeTransfer/Mocker/releases/tag/2.1.0) :rocket:

**Comment by ghost** [comment]
Congratulations! :tada: This was released as part of [Release 2.1.0](https://github.com/WeTransfer/Mocker/releases/tag/2.1.0) :rocket:

**Comment by ghost** [comment]
Congratulations! :tada: This was released as part of [Release 2.1.0](https://github.com/WeTransfer/Mocker/releases/tag/2.1.0) :rocket:

**Comment by ghost** [comment]
Congratulations! :tada: This was released as part of [Release 2.1.0](https://github.com/WeTransfer/Mocker/releases/tag/2.1.0) :rocket:

**Pull request merged**
