### PR TITLE
Add Doc-C start

### PR DESCRIPTION
**Pull request by AvdLee**
Adds a start for Doc-C documentation, together with a workflow to automatically deploy.

### CODE REVIEW

**Comment by wetransferplatform** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>Testing cancelled because the build failed.</td>
    </tr>
  
<tr>
      <td>:no_entry_sign:</td>
      <td>Cannot convert value of type 'MockedData.Type' to expected argument type 'AnyClass' (aka 'any AnyObject.Type')</td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>Run script build phase 'SwiftLint' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase.</td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>

  View more details on <a href="https://app.bitrise.io/build/ecebd914-34b3-4ff0-9991-f6a5437447d9" target="_blank">Bitrise</a>
  </td>
    </tr>
  </tbody>
</table>

### SwiftLint found issues

| Severity | File | Reason |
| -------- | ---- | ------ |
Warning | Mocker.swift:96 | Line should be 140 characters or less: currently 149 characters (`line_length`) |
Error | MockingURLProtocol.swift:40 | Line should be 160 characters or less: currently 166 characters (`line_length`) |
Error | MockingURLProtocol.swift:43 | Line should be 160 characters or less: currently 200 characters (`line_length`) |
Warning | MockingURLProtocol.swift:100 | Line should be 140 characters or less: currently 145 characters (`line_length`) |
Error | MockingURLProtocol.swift:104 | Line should be 160 characters or less: currently 221 characters (`line_length`) |
Error | Mock.swift:8 | Line should be 160 characters or less: currently 177 characters (`line_length`) |
Warning | Mock.swift:48 | Line should be 140 characters or less: currently 155 characters (`line_length`) |
Error | Mock.swift:80 | Line should be 160 characters or less: currently 211 characters (`line_length`) |
Error | Mock.swift:83 | Line should be 160 characters or less: currently 208 characters (`line_length`) |
Error | Mock.swift:92 | Line should be 160 characters or less: currently 287 characters (`line_length`) |
Warning | Mock.swift:121 | Line should be 140 characters or less: currently 142 characters (`line_length`) |
Warning | Mock.swift:128 | Line should be 140 characters or less: currently 141 characters (`line_length`) |
Error | Mock.swift:135 | Line should be 160 characters or less: currently 246 characters (`line_length`) |
Error | Mock.swift:136 | Line should be 160 characters or less: currently 236 characters (`line_length`) |
Warning | Mock.swift:147 | Line should be 140 characters or less: currently 150 characters (`line_length`) |
Warning | Mock.swift:148 | Line should be 140 characters or less: currently 153 characters (`line_length`) |
Warning | Mock.swift:184 | Line should be 140 characters or less: currently 157 characters (`line_length`) |
Error | Mock.swift:194 | Line should be 160 characters or less: currently 168 characters (`line_length`) |
Warning | MockerTests.swift:244 | Line should be 140 characters or less: currently 154 characters (`line_length`) |
Warning | MockerTests.swift:52 | Chained function calls should be either on the same line, or one per line. (`multiline_function_chains`) |
Warning | MockerTests.swift:71 | Chained function calls should be either on the same line, or one per line. (`multiline_function_chains`) |
Warning | MockerTests.swift:94 | Chained function calls should be either on the same line, or one per line. (`multiline_function_chains`) |
Warning | MockerTests.swift:116 | Chained function calls should be either on the same line, or one per line. (`multiline_function_chains`) |
Warning | MockerTests.swift:148 | Chained function calls should be either on the same line, or one per line. (`multiline_function_chains`) |
Warning | MockerTests.swift:167 | Chained function calls should be either on the same line, or one per line. (`multiline_function_chains`) |
Warning | MockerTests.swift:188 | Chained function calls should be either on the same line, or one per line. (`multiline_function_chains`) |
Warning | MockerTests.swift:211 | Chained function calls should be either on the same line, or one per line. (`multiline_function_chains`) |
Warning | MockerTests.swift:264 | Chained function calls should be either on the same line, or one per line. (`multiline_function_chains`) |
Warning | MockerTests.swift:446 | Chained function calls should be either on the same line, or one per line. (`multiline_function_chains`) |
Warning | MockerTests.swift:479 | Chained function calls should be either on the same line, or one per line. (`multiline_function_chains`) |

## Code Coverage Report
| Name | Coverage ||
| --- | --- | --- |

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/swift">Danger Swift</a> against 6fea8cf987581ef8c354a9973fead4fd582b8e5a
</p>

**Comment by amirdew** [comment]
Is this ready to review? seems like a draft

**Review by amirdew — COMMENTED** [review]
Is this ready to review? seems like a draft

**Comment by AvdLee** [comment]
@amirdew changed it to draft indeed, I need to do some more polishing before we can push this.

**Comment by AvdLee** [comment]
Closing for now since we don't have the priority to work on this.

**Pull request closed without merging**
