### PR TITLE
Enable post body checks

### PR DESCRIPTION
**Pull request by AvdLee**
This allows us to verify the post body parameters 🚀

### CODE REVIEW

**Comment by ghost** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  Consider to place some `MARK:` lines for Sources/Mock.swift, which is over 200 lines big.
  </td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>

  View more details on <a href="https://app.bitrise.io/build/80bb40d7d971f5bb" target="_blank">Bitrise</a>
  </td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>Mocker: Executed 17 tests, with 0 failures (0 unexpected) in 1.721 (1.757) seconds</td>
    </tr>
  </tbody>
</table>

## Mocker.framework: Coverage: 88.4
| File | Coverage ||
| --- | --- | --- |
MockingURLProtocol.swift | 87.76% | ✅
Mock.swift | 84.44% | ✅

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/swift">Danger Swift</a> against ba110e50f7778e6585de7d701a0db4eaf5e7be06
</p>

**Review by kairadiagne — APPROVED** [review]

**Comment by ghost** [comment]
Congratulations! :tada: This was released as part of [Release 2.1.0](https://github.com/WeTransfer/Mocker/releases/tag/2.1.0) :rocket:

**Comment by ghost** [comment]
Congratulations! :tada: This was released as part of [Release 2.1.0](https://github.com/WeTransfer/Mocker/releases/tag/2.1.0) :rocket:

**Comment by ghost** [comment]
Congratulations! :tada: This was released as part of [Release 2.1.0](https://github.com/WeTransfer/Mocker/releases/tag/2.1.0) :rocket:

**Pull request merged**
